api_version: '1'
name: pandora-cli
description: Pandora Toolbox CLI is an automation and integration tool for small tasks.
authors:
  - Artemis Resende (contact@aresende.com)
command: pandora
version: ${PANDORA_VERSION}
preferences:
  command_delay: 0.1
  lang: en_US.utf-8
  environment: ${PANDORA_RUNTIME_ENV}
collections:
  - ${PANDORA_HOME}/plugins
